name: Deploy MkDocs
on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install mkdocs mkdocs-material mkdocs-glightbox

      - run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site                  # mkdocs default output dir
          branch: gh-pages              # your Pages source branch
          token: ${{ secrets.GITHUB_TOKEN }}   # automatic, no need to set manually
          clean: false                  # IMPORTANT: false prevents wiping other folders (like dev/)
          target-folder: ${{ github.ref_name == 'main' && '.' || github.ref_name }}
